= Dashboard UI
Anthony Ikeda <anthony.ikeda@gmail.com>
Version 0.0.1
:listing-caption: Listing

== Overview

This is a base for attempting to determine how to use WebAssembly with Angular 9.

First attempt uses the embedded wasm approach where we inlude the built wasm with the Angular app:

* `src/app/assembly/stats_client_wasm_b.wasm`
* `src/app/assembly/stats_client_wasm.js`

The WebAssembly component used is stored here: https://github.com/anthonyikeda/stats-client

== Reference

Here are some articles and repos that I've been using to try and make this work.

* https://github.com/boyanio/angular-wasm
* https://boyan.io/angular-wasm
* https://developers.google.com/web/updates/2018/04/loading-wasm
* https://prestonrichey.com/blog/react-rust-wasm/
* https://github.com/ballercat/wasm-loader
* https://malcoded.com/posts/web-assembly-angular/

== WebAssembly Component

The WebAssembly was packaged with https://rustwasm.github.io/wasm-pack/[wasm-pack] and targetted to `web` as the compilation.

The `stats_client_wasm.js` and `stats_client_wasm_d.wasm` files were then copied to the `src/app/assembly` directory.

There is also a nodejs packaged version attached to the package.json but not imported into the project just yet - got to work out how to use it.
